version: 0.1
##run-as: ec2-user
env:
  #shell: shell-tag
  variables:
    kongToken: "kpat_0fRrY2grSEAbJ7Hw8fQfcmupGxYTdRi80AqpHrZ3i1IgTrPJv"
    #key: "value"
  #parameter-store:
   # key: "value"
   # key: "value"
  #exported-variables:
  #  - variable
  #  - variable
  #secrets-manager:
  #  key: secret-id:json-key:version-stage:version-id
  #git-credential-helper: no | yes
  
phases:
  install:
    commands:
      #- sudo yum install python-jinja2
      - pip3 -V
      - pip3 install jinja2
      - pip3 install PyYAML
      ## - echo "deb [trusted=yes arch=amd64] https://download.konghq.com/insomnia-ubuntu/ default all" | sudo tee -a /etc/apt/sources.list.d/insomnia.list
      ## - sudo apt-get update -y
      ## - sudo apt-get install insomnia -y
      # Download Inso CLI tar file
      - curl -sL "$insolib" -o inso-linux.xz && tar -xf inso-linux.xz -C /tmp && sudo cp /tmp/inso /usr/local/bin/ && inso --version
      # Unzip the inso CLI compressed file
      ## - tar -xf inso-linux.xz -C /tmp
      # Copy inso cli file from tmp directory to bin 
      ## - sudo cp /tmp/inso /usr/local/bin/
      # Download Deck CLI file
      - curl -sL "$decklib" -o deck.tar.gz && tar -xf deck.tar.gz -C /tmp && sudo cp /tmp/deck /usr/local/bin/ && deck version && pwd
      # Unzip deck CLI tar file
      ## - tar -xf deck.tar.gz -C /tmp
      # copy deck file from tmp to bin directory
      ## - sudo cp /tmp/deck /usr/local/bin/
      ## - deck version
      ## - inso --version
      ## - pwd
     
  build:
    commands:
      # export api spec 
      - inso export spec "$apispecname" > "$apispecname"
      #verify the exported api spec
      - inso lint spec Petstore.yaml
      #generate declarative from open api spec
      - inso generate config Petstore.yaml --type declarative > PetstoreKongDecl.yaml
      #convert version of declarative file from previous version to 3.x
      - deck convert --from kong-gateway-2.x --to kong-gateway-3.x --input-file PetstoreKongDecl.yaml --output-file PetstoreKongDecl3.yaml
      #validate the declarative spec generated
      - deck validate -s PetstoreKongDecl3.yaml
      #run the test suite
      - inso run test PetTestSuite
      #sync the declarative to kong runtime using deck
      ## - deck sync --kong-addr http://3.236.54.44:8001 --select-tag "Petstore" -s "PetstoreKongDecl3.yaml" --workspace "kongdemo" --headers "kong-admin-token:JUR0t0Y6e07JBw4sj87L0pIuEloQ9Rer"
      - deck sync --select-tag "Petstore" -s "PetstoreKong.yaml" --konnect-token $kongToken 
      #publish open api specification to dev portal
      ##- curl -i -X PUT http://3.236.54.44:8001/kongdemo/files/specs/Petstore.yaml -F "contents=@Petstore.yaml" --header "kong-admin-token:JUR0t0Y6e07JBw4sj87L0pIuEloQ9Rer"
