openapi: 3.0.0
info:
  title: BookAPI
  description: This is Book API for Book Management
  version: v1
servers:
- url: http://anypoint.mulesoft.com/mocking/api/v1/links/fe339c3c-256f-441a-a22a-b9271490b170
- url: https://anypoint.mulesoft.com/mocking/api/v1/links/fe339c3c-256f-441a-a22a-b9271490b170
paths:
  /book:
    get:
      operationId: Get a Book Object
      parameters:
      - name: bookid
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: number
          format: int
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookType'
    post:
      operationId: Add a New Book
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookType'
            example:
              BookID: 120
              BookTitile: Programming Amazon EC2
              BookAuthor:
              - Jurg Vliet
              - FlaviaPagenelli
              BookPrice?: 400
        required: true
      responses:
        201:
          content:
            application/json:
              schema:
                example:
                  message: Book Created Successfully
components:
  schemas:
    BookType:
      required:
      - BookAuthor
      - BookID
      - BookTitile
      type: object
      properties:
        BookID:
          type: number
          format: int
          example: 1
        BookTitile:
          type: string
          example: Example
        BookAuthor:
          type: string
        BookPrice:
          type: number
          format: int
          example: 1
      description: Book Customer Object
      example:
        BookID: 100
        BookTitile: Mule Cloud Connect
        BookAuthor:
        - Rayun carter
        - Ajmal
        BookPrice: 300
  responses: {}
  parameters: {}
  examples: {}
  requestBodies: {}
  headers: {}
  securitySchemes: {}
  links: {}
  callbacks: {}
