openapi: 3.0.0
info:
  title: Customer API
  version: v1.0
servers:
- url: http://localhost:80/api
paths:
  /v1/customers:
    get:
      description: Returns list of customers
      operationId: Get Customers
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customers'
components:
  schemas:
    Customers:
      type: array
      example:
      - id: 4789
        customerName: Robert DeNiro
      - id: 36987
        customerName: Al Pacino
      items:
        $ref: '#/components/schemas/Customer'
    Customer:
      required:
      - customerName
      - id
      type: object
      properties:
        id:
          type: integer
          description: Identifier of customer
        customerName:
          type: string
          description: Customer Name
      description: Customer information
  responses: {}
  parameters: {}
  examples: {}
  requestBodies: {}
  headers: {}
  securitySchemes: {}
  links: {}
  callbacks: {}
