openapi: 3.0.0
info:
  title: ProductAPI
  version: undefined
servers:
- url: https://anypoint.mulesoft.com/mocking/api/v1/links/4d03299d-8c6c-4b85-b637-422636b61985
paths:
  /products:
    get:
      operationId: GET_products
      responses:
        200:
          content:
            application/json:
              schema:
                example:
                - productId: 1
                  productName: iphone 13 mini
                - productId: 2
                  productName: Samsung Galaxy S21
    post:
      operationId: POST_products
      requestBody:
        content:
          application/json:
            schema:
              type: string
            example:
              ProductId: 2
              ProductName: Samsung Galaxy S21
        required: true
      responses:
        201:
          content:
            application/json:
              schema:
                example:
                  message: New product has been added
components:
  schemas: {}
  responses: {}
  parameters: {}
  examples: {}
  requestBodies: {}
  headers: {}
  securitySchemes: {}
  links: {}
  callbacks: {}
