openapi: 3.0.0
info:
  title: SampleAPI
  version: undefined
servers:
- url: https://anypoint.mulesoft.com/mocking/api/v1/links/1a41d65c-7138-44eb-9525-3c139da0ef41
paths:
  /search:
    get:
      operationId: GET_search
      parameters:
      - name: keyword
        in: query
        required: true
        style: form
        explode: true
        schema:
          maxLength: 10
          minLength: 3
          type: string
      responses:
        200:
          content:
            application/json:
              schema:
                example:
                  message: result returned successful"
components:
  schemas: {}
  responses: {}
  parameters: {}
  examples: {}
  requestBodies: {}
  headers: {}
  securitySchemes: {}
  links: {}
  callbacks: {}
