_format_version: "1.1"
_info:
 select_tags:
 - productapi_oaspec
services:
  - name: ProductAPI
    protocol: https
    host: anypoint.mulesoft.com
    port: 443
    path: /mocking/api/v1/links/4d03299d-8c6c-4b85-b637-422636b61985
    plugins: []
    routes:
      - tags:
          - OAS3_import
          - OAS3file_productapi_oaspec.yaml
        name: ProductAPI-GET_products
        methods:
          - GET
        paths:
          - /products$
        strip_path: false
      - tags:
          - OAS3_import
          - OAS3file_productapi_oaspec.yaml
        name: ProductAPI-POST_products
        methods:
          - POST
        paths:
          - /products$
        strip_path: false
    tags:
      - OAS3_import
      - OAS3file_productapi_oaspec.yaml

